# A simple publishing platform powered by Supranim,
# a modern web framework for Nim.
#
# (c) 2026 George Lemon | AGPLv3 License
#     Made by Humans from OpenPeeps
#     https://github.com/openpeeps/sunday

import std/[os, tables, times]

import pkg/[pluginkit, openparser/json]
import pkg/ozark/driver/psql
import pkg/libevent/bindings/http
import pkg/supranim/core/[application, router,
                      request, response, services]
export pluginkit

import ./logger, ./db

## This service provides a pluggable architecture for the
## application, allowing developers to create and register
## plugins that can extend the functionality of the app.
## 
## It uses the `pluginkit` package to manage plugins and
## their lifecycle.

initService SundayPluginManager[Singleton]:
  ## A singleton of `PluginManager` from the `pluginkit` package.
  backend do:
    type
      SundayPluginManager* = ref object        
        manager*: PluginManager
          ## The `PluginManager` instance part of the pluginkit package
        onInstall*: OrderedTableRef[NanoID, RuntimeSchemas]
        onUninstallAliases*: TableRef[string, NanoID]
          ## A table mapping table name to plugin ID for
          ## uninstalling tables during plugin uninstallation
          ## based on the collected schemas in the `onInstall` table
      
      # plugin_callback_fn* = proc (req: ptr Request, res: ptr Response) {.cdecl.}
      plugin_callback_fn* = proc (): cstring {.cdecl.}
  client do:
    # fwd declarations
    proc onPluginLoaded(plugin: Plugin)
    proc onPluginUnloaded(plugin: Plugin)
    proc onPluginError(plugin: Plugin, error: string)

    proc pluginManager*: ptr SundayPluginManager {.inline.} =
      ## Returns the Singleton instance of the SundayPluginManager
      getSundayPluginManagerInstance(
        proc(instance: ptr SundayPluginManager) =
          {.gcsafe.}:
            new(instance[])
            # set the callbacks for plugin events when the instance is created
            instance[].onInstall = newOrderedTable[NanoID, RuntimeSchemas]()
            instance[].onUninstallAliases = newTable[string, NanoID]()
            instance[].manager = PluginManager(callbacks:
              PluginManagerCallbacks(
                onLoad: onPluginLoaded,
                onUnload: onPluginUnloaded,
                onError: onPluginError
              )
            )
            logger("Service Pluggable: Initialized PluginManager singleton with event callbacks")
      ) # auto generated by the service manager

    proc onPluginLoaded(plugin: Plugin) =
      # All Sunday plugins must provide a serialized schema for database
      # models, controllers, and other components that they define (if any).

      # Collect Database Schemas
      let runtimeSchema = unserializeSchemas(plugin.getSchemas())
      if runtimeSchema != nil:
        # collect any database tables defined in the plugin's schema

        # even if the schema has been validated during plugin compilation,
        # we still want to validate when loading the plugin at runtime to catch any potential issues before
        # registering components with the application
        # TODO

        # store the plugin's runtime schema in the `onInstall` table for later
        # use during plugin installation triggered from the dashboard UI
        pluginManager().onInstall[plugin.getId()] = runtimeSchema
        
        logger("PluginManager loaded plugin: " & plugin.getId())

      # load static files bundled with the plugin `plugin_event_load_static_files`
      let eventLoadFilesFn = cast[plugin_event_load_fn](plugin.getHandle.symAddr("plugin_event_load_static_files"))
      if eventLoadFilesFn != nil:
        let staticTemplates = cstrToString(eventLoadFilesFn())
        let filesTable = json.fromJson(staticTemplates, TableRef[string, string])
        # if filesTable.hasKey("templates"):
        #   echo "Plugin " & plugin.name & " has templates: " & $filesTable["templates"]
        # if filesTable.hasKey("readme.md"):
        #   echo "Plugin " & plugin.name & " has readme: " & $filesTable["readme.md"]
        plugin.staticTemplates = filesTable

      # load plugin routes when the plugin defines a `plugin_event_load_routes`
      let eventLoadRoutesFn = cast[plugin_event_load_fn](plugin.getHandle.symAddr("plugin_event_load_routes"))
      if eventLoadRoutesFn != nil:
        let routes = cstrToString(eventLoadRoutesFn())
        plugin.registerRoutes = fromJson(routes, JsonNode)

    proc onPluginUnloaded(plugin: Plugin) =
      logger("PluginManager unloaded plugin: " & plugin.getId())

    proc onPluginError(plugin: Plugin, error: string) =
      discard

    proc onInstallCallback*(plugin: Plugin) =
      ## This callback is not part of the pluginkit package, instead it is a 
      ## custom callback defined at the Sunday application level to handle
      ## plugin installation events triggered from the dashboard UI via control handlers.

      var pluginNavigation = newJObject()
      # try to load a navigation schema from the plugin if any
      let navigationFn = cast[plugin_event_load_fn](plugin.getHandle.symAddr("plugin_event_load_navigation"))
      
      if navigationFn != nil:
        # load the navigation schema and decode it to JSON Node
        pluginNavigation = fromJson(cstrToString(navigationFn()))

      withDBPool do:
        # store the available navigation items for the plugin
        # in the database as part of the plugin's settings
        Models.table(Plugins).insert({
          "id": plugin.getId(),
          "status": "1", # mark as installed
          "settings_schema": toJson(%*{
            "navigation": pluginNavigation
          }),
          "installed_at": $(now())
        }).exec()
      
      # if the plugin defines routes, we can register via the application's router
      # let callbackFn = cast[plugin_callback_fn](plugin.getHandle.symAddr("getMedia"))
      # if callbackFn != nil:
      #   echo "Registering plugin callback for route /plugin-link"
      #   App.router.registerRoute("/dashboard/media2", HttpGet, proc(req: var Request, res: var Response) =
      #     req.send(200, "Hello from plugin callback!")
      #   )
      # register available routes for the plugin during installation
      # for key, routeObj in plugin.registerRoutes:
      #   echo key

    const pluginsDir = "plugins"
    const pluginExt =
      when defined(windows): ".dll"
      elif defined(macosx): ".dylib"
      else: ".so" # default to .so for Linux and other Unix-like systems
      
    proc init*(app: Application) =
      ## Initialize an instance of the PluginManager when the
      ## service is initialized. This will allow plugins to be
      ## loaded and managed throughout the application.
      let pluginsPath = app.paths().getInstallationPath / pluginsDir
      
      # the current directory is always the root of the Booyaka project,
      # so we can use it to construct the path to the plugins directory 
      discard existsOrCreateDir(pluginsPath)
      for path in walkFiles(pluginsPath / "*"):
        if path.splitFile.ext == pluginExt:
          let pluginId = pluginManager().manager.load(path)
      